name: Test and Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      icecast_user: ${{ secrets.icecast_user }}
      icecast_pass: ${{ secrets.icecast_pass }}
      VIC_user: ${{ secrets.VIC_USER }}
      VIC_password: ${{ secrets.VIC_PASSWORD }}
      BF_pass: ${{ secrets.BF_pass }}
      IPInfoToken: ${{ secrets.IPINFOTOKEN }}
      mail_server_external: ${{ secrets.mail_server_external }}
      
    steps:

    - name: prep action  
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest